fix: #main change tag workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,6 +4,12 @@ on:
   push:
     branches:
       - main
+  workflow_dispatch:
+    inputs:
+      version_type:
+        description: 'Select version type (major, minor, fix)'
+        required: true
+        default: 'fix'
 
 permissions:
   contents: write
@@ -19,7 +25,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Generate new tag
+      - name: Generate new tag based on version type
         id: generate_tag
         run: |
           git fetch --tags
@@ -38,9 +44,26 @@ jobs:
             minor=$(echo "$base_version" | cut -d'.' -f2)
             patch=$(echo "$base_version" | cut -d'.' -f3)
           
-            new_patch=$((patch + 1))
+            case "${{ github.event.inputs.version_type }}" in
+              major)
+                major=$((major + 1))
+                minor=0
+                patch=0
+                ;;
+              minor)
+                minor=$((minor + 1))
+                patch=0
+                ;;
+              fix)
+                patch=$((patch + 1))
+                ;;
+              *)
+                echo "Invalid version type: ${{ github.event.inputs.version_type }}. Use 'major', 'minor', or 'fix'."
+                exit 1
+                ;;
+            esac
           
-            new_tag="v${major}.${minor}.${new_patch}"
+            new_tag="v${major}.${minor}.${patch}"
           else
             new_tag="v0.0.1"
           fi
