feat: #dev new tagging

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,7 +25,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Generate new tag based on commit messages
+      - name: Wait for version type input
+        id: wait_for_version
+        run: |
+          echo "Waiting for version_type to be selected"
+          echo "version_type=${{ github.event.inputs.version_type }}" >> $GITHUB_ENV
+
+      - name: Generate new tag based on version type
         id: generate_tag
         run: |
           git fetch --tags
@@ -46,41 +52,12 @@ jobs:
             major=0
             minor=0
             patch=0
-            latest_tag="HEAD"  # Domyślnie HEAD, gdy brak poprzedniego tagu
+            latest_tag="HEAD"
           fi
 
-          # Sprawdzamy commit messages od ostatniego tagu
-          commits=$(git log ${latest_tag}..HEAD --pretty=%B 2>/dev/null || echo "")
+          version_type="${{ env.version_type }}"
 
-          # Ustawiamy domyślnie patch
-          version_type="patch"
-          has_feat_commit=false
-          has_fix_commit=false
-          has_release_commit=false
-
-          # Sprawdzamy, czy są commity feat, fix lub Release
-          if echo "$commits" | grep -q '^feat'; then
-            has_feat_commit=true
-          fi
-
-          if echo "$commits" | grep -q '^fix'; then
-            has_fix_commit=true
-          fi
-
-          if echo "$commits" | grep -q 'Release'; then
-            has_release_commit=true
-          fi
-
-          # Priorytetowo traktujemy 'Release' -> 'feat' -> 'fix'
-          if [ "$has_release_commit" = true ]; then
-            version_type="major"
-          elif [ "$has_feat_commit" = true ]; then
-            version_type="minor"
-          elif [ "$has_fix_commit" = true ]; then
-            version_type="patch"
-          fi
-
-          # Zwiększamy odpowiednią wersję
+          # Zwiększamy odpowiednią wersję na podstawie ręcznego wyboru
           case $version_type in
             "major")
               major=$((major + 1))
@@ -94,11 +71,15 @@ jobs:
             "patch")
               patch=$((patch + 1))
               ;;
+            *)
+              echo "Invalid version type selected!"
+              exit 1
+              ;;
           esac
 
           new_tag="v${major}.${minor}.${patch}"
 
-          echo "Detected version type: $version_type"
+          echo "Selected version type: $version_type"
           echo "New tag: $new_tag"
           echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
 
